from typing import Protocol

from app.domain.models import Issue, IssueChanges, IssueFilters, IssueStatus, NewIssue, User


class UserRepository(Protocol):
    async def get_by_username(self, username: str) -> User | None: ...

    async def save(self, user: User) -> None: ...


class IssueRepository(Protocol):
    async def list(self, filters: IssueFilters, limit: int) -> list[Issue]: ...

    async def get(self, issue_id: str) -> Issue | None: ...

    async def create(self, new_issue: NewIssue) -> Issue: ...

    async def update(self, issue_id: str, changes: IssueChanges) -> Issue | None: ...

    async def count_by_status(self) -> dict[IssueStatus, int]: ...
